#!/usr/bin/env python3
"""Embed HTML templates from templates/ into src/templates_embedded.h as C++ raw string literals."""

import os

TEMPLATES_DIR = "templates"
OUTPUT_FILE = "src/templates_embedded.h"

# Pick a delimiter not present in any template content
DELIMITER = "T0000"

def main():
    templates = {}
    for fname in sorted(os.listdir(TEMPLATES_DIR)):
        if not fname.endswith(".html"):
            continue
        with open(os.path.join(TEMPLATES_DIR, fname)) as f:
            content = f.read()
        if DELIMITER in content:
            raise SystemExit(f"Delimiter {DELIMITER} found in {fname}, pick a different one")
        templates[fname] = content

    with open(OUTPUT_FILE, "w") as out:
        out.write("// Auto-generated by scripts/embed_templates.py — do not edit\n")
        out.write("#pragma once\n")
        out.write("#include <string>\n")
        out.write("#include <unordered_map>\n\n")
        out.write("namespace pinklib {\n\n")
        out.write("inline const std::unordered_map<std::string, std::string>& embedded_templates() {\n")
        out.write("    static const std::unordered_map<std::string, std::string> t = {\n")
        for name, content in sorted(templates.items()):
            out.write(f'        {{"{name}", R"{DELIMITER}(\n{content}\n){DELIMITER}"}},\n')
        out.write("    };\n")
        out.write("    return t;\n")
        out.write("}\n\n")
        out.write("} // namespace pinklib\n")
    print(f"Embedded {len(templates)} templates into {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
